[project]
name = "ddi-trainer"
base_image = "runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04"
gpu_types = ["NVIDIA RTX A4000", "NVIDIA RTX A5000", "NVIDIA RTX A6000", "NVIDIA GeForce RTX 4090"]
gpu_count = 1
volume_mount_path = "/runpod-volume"

[project.env_vars]

[runtime]
handler_path = "handler.py"
requirements_path = "requirements.txt"
